kind: pipeline
type: docker
name: deploy_production

steps:
- name: build_and_deploy
  # Temporary use this due to a bug with plugins/docker
  image: techknowlogick/drone-docker
  settings:
    repo: registry.dewardt.uk/doxa/server
    username: doxa
    password:
      from_secret: DOCKER_PASSWORD
    registry: registry.dewardt.uk
    dockerfile: dev/server/Dockerfile

# https://docs.drone.io/promote/ - NOTE: in future it could be a good idea to always build but only deploy on promote
# this is done with a when clause
trigger:
  event:
  - promote
  target:
  - production
---
kind: pipeline
type: docker
name: frontend

workspace:
  path: aisoc_ui

steps:
- name: install and build
  image: node
  commands:
  - npm install
  - npm run build

trigger:
  event:
  - push
  - pull_request
