kind: pipeline
type: docker
name: deploy_production

steps:
- name: build_and_deploy
  image: plugins/docker
  settings:
    repo: louis/doxa_server
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    password:
      from_secret: DOCKER_PASSWORD
    dockerfile: dev/server/Dockerfile

# https://docs.drone.io/promote/ - NOTE: in future it could be a good idea to always build but only deploy on promote
# this is done with a when clause
trigger:
  event:
  - promote
  target:
  - production
