[package]
name = "doxa_executor"
version = "0.1.0"
edition = "2018"

[dependencies]
doxa_core = { path = "../doxa_core" }
doxa_mq = { path = "../doxa_mq" }

async-trait = "0.1.51"
wasmer = "2.0.0"
serde = { version = "1.0.127", features = ["derive"] }
